[package]
name = "pineapple-data"
version = "0.0.4"
edition = "2024"
publish = false

[dependencies]
pineapple_core = { path = "../pineapple-core", package = "pineapple-core" }
reqwest = { version = "0.12.12", features = ["cookies"] }
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0"
scraper = "0.12"
dirs = "4.0"
kdam = { version = "0.6.1", features = ["template", "rayon"] }
