[workspace]
members = [
    "pineapple-cli",
    "pineapple-core",
    "pineapple-data",
    "pineapple-neural",
]
resolver = "2"

[workspace.package]
version = "0.0.2"
edition = "2024"
description = "Simplified processing for image-based cell profiling with pineapple"
readme = "README.md"
repository = "https://github.com/tomouellette/pineapple"
categories = ["science"]
license = "GNU GPLv3"
keywords = [
    "morphological-variation",
    "morphological-profiling",
    "image-processing",
    "bio-imaging",
    "phenotypic-screening",
    "microscopy",
    "image-analysis",
]

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release]
strip = true
lto = true
